# Generated by Django 5.0.4 on 2024-05-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_borrowing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowing',
            old_name='date_returned',
            new_name='return_date',
        ),
        migrations.AddField(
            model_name='borrowing',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
